select ORDERS.BRANCH_NO,sum(ORDERS.SUBTOTAL), sum(ORDERS.TAX_AMT),
sum(ORDERS.TOTAL_AMT),sum(ORDERS.SHIPPING_CHARGE)
FROM ORDERS
GROUP BY ORDERS.BRANCH_NO;


select O.BRANCH_NO,sum(O.SUBTOTAL), sum(O.TAX_AMT),
sum(O.TOTAL_AMT),sum(O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY ROLLUP(O.BRANCH_NO);


select O.BRANCH_NO,sum(O.SUBTOTAL), sum(O.TAX_AMT),
sum(O.TOTAL_AMT),sum(O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY CUBE(O.BRANCH_NO);


select O.BRANCH_NO,sum(O.SUBTOTAL), sum(O.TAX_AMT),
sum(O.TOTAL_AMT),sum(O.SHIPPING_CHARGE),ROW_NUMBER() OVER(ORDER BY SUM(SUBTOTAL)) RowNumber
FROM ORDERS O
GROUP BY (O.BRANCH_NO);


SELECT ORDERS.BRANCH_NO,sum(ORDERS.SUBTOTAL), sum(ORDERS.TAX_AMT),
sum(ORDERS.TOTAL_AMT),sum(ORDERS.SHIPPING_CHARGE),
SUM(ORDERS.SUBTOTAL)*100/SUM(SUM(ORDERS.SUBTOTAL)) OVER() AS PERCENTAGE
FROM ORDERS
GROUP BY ORDERS.BRANCH_NO;


SELECT O.EMPLOYEE_NO, SUM(O.SUBTOTAL), SUM(O.TAX_AMT),
SUM(O.TOTAL_AMT),SUM( O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY O.EMPLOYEE_NO;


SELECT O.EMPLOYEE_NO, SUM(O.SUBTOTAL), SUM(O.TAX_AMT),
SUM(O.TOTAL_AMT),SUM( O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY ROLLUP(O.EMPLOYEE_NO);


SELECT O.EMPLOYEE_NO, SUM(O.SUBTOTAL), SUM(O.TAX_AMT),
SUM(O.TOTAL_AMT),SUM( O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY CUBE(O.EMPLOYEE_NO);


SELECT O.EMPLOYEE_NO, SUM(O.SUBTOTAL), SUM(O.TAX_AMT),
SUM(O.TOTAL_AMT),SUM( O.SHIPPING_CHARGE)
FROM ORDERS O
GROUP BY ROLLUP(O.EMPLOYEE_NO);



SELECT O.EMPLOYEE_NO, SUM(O.SUBTOTAL), SUM(O.TAX_AMT),
SUM(O.TOTAL_AMT),SUM( O.SHIPPING_CHARGE), SUM(O.SUBTOTAL)*100/SUM(SUM(O.SUBTOTAL)) OVER() AS PERCENTAGE
FROM ORDERS O
GROUP BY O.EMPLOYEE_NO;



SELECT * FROM ORDERS;
SELECT PRODUCT.PRODUCT_NO, PRODUCT.PRODUCT_CATEGORY, ORDERLINE.QTY
FROM PRODUCT
JOIN ORDERLINE ON PRODUCT.PRODUCT_NO = ORDERLINE.PRODUCT_NO;
