SELECT BOOK_CODE, TITLE 
FROM BOOK 
WHERE TYPE = 'FIC' OR TYPE = 'MYS' OR TYPE = 'ART' 
ORDER BY TITLE;

SELECT BOOK_CODE, TITLE 
FROM BOOK 
WHERE TYPE = 'MYS' AND PRICE < 20;

SELECT BOOK_CODE, TITLE, PRICE 
FROM BOOK 
WHERE PRICE > 10 AND PRICE < 20;


SELECT PUBLISHER_NAME 
FROM PUBLISHER 
WHERE PUBLISHER_NAME LIKE '% and%';

SELECT BOOK_CODE 
FROM BOOK 
WHERE TITLE = NULL;

SELECT BOOK_CODE, TITLE, PRICE 
FROM BOOK 
ORDER BY TITLE,PRICE DESC;


SELECT COUNT (DISTINCT TYPE) AS BOOK_TYPE_NUMBER 
FROM BOOK;


SELECT DISTINCT TYPE, AVG(PRICE) 
FROM BOOK WHERE PAPERBACK = 'Y' GROUP BY TYPE;


SELECT TYPE, AVG(PRICE) 
FROM BOOK 
WHERE PAPERBACK = 'Y' AND PRICE > 10 GROUP BY TYPE;

SELECT AUTHOR.AUTHOR_LAST, AUTHOR.AUTHOR_FIRST 
FROM AUTHOR 
JOIN WROTE ON AUTHOR.AUTHOR_NUM = WROTE.AUTHOR_NUM 
JOIN BOOK ON BOOK.BOOK_CODE = WROTE.BOOK_CODE 
JOIN PUBLISHER ON PUBLISHER.PUBLISHER_CODE = BOOK.PUBLISHER_CODE 
WHERE PUBLISHER.CITY = 'Boston';

SELECT TITLE, PRICE 
FROM BOOK WHERE (SELECT AVG(BOOK.PRICE) AS AVERAGE FROM BOOK )> PRICE
ORDER BY PRICE;

SELECT BOOK.BOOK_CODE, BOOK.TITLE 
FROM BOOK 
JOIN PUBLISHER ON BOOK.PUBLISHER_CODE = PUBLISHER.PUBLISHER_CODE 
WHERE PUBLISHER.CITY = 'New York';

SELECT BOOK_CODE, TITLE, PRICE 
FROM BOOK 
WHERE PRICE > (SELECT MIN(PRICE) FROM BOOK WHERE TYPE = 'FIC');

SELECT BOOK_CODE, TITLE, PRICE 
FROM BOOK 
WHERE PRICE > (SELECT MAX(PRICE) FROM BOOK WHERE TYPE = 'FIC');

SELECT DISTINCT AUTHOR.AUTHOR_LAST, COUNT(AUTHOR.AUTHOR_NUM) 
FROM AUTHOR 
JOIN WROTE ON WROTE.AUTHOR_NUM = AUTHOR.AUTHOR_NUM 
GROUP BY AUTHOR.AUTHOR_LAST;

SELECT BOOK.BOOK_CODE, BOOK.TITLE 
FROM BOOK JOIN INVENTORY ON INVENTORY.BOOK_CODE = BOOK.BOOK_CODE 
JOIN WROTE ON WROTE.BOOK_CODE = BOOK.BOOK_CODE 
WHERE INVENTORY.BRANCH_NUM = '2' AND WROTE.AUTHOR_NUM = '20';

SELECT AUTHOR.AUTHOR_NUM, AUTHOR.AUTHOR_LAST, COUNT(AUTHOR.AUTHOR_NUM) 
FROM AUTHOR 
JOIN WROTE ON WROTE.AUTHOR_NUM = AUTHOR.AUTHOR_NUM 
GROUP BY AUTHOR.AUTHOR_NUM, AUTHOR.AUTHOR_LAST;

SELECT BOOK.BOOK_CODE 
FROM BOOK LEFT OUTER JOIN INVENTORY ON INVENTORY.BOOK_CODE = BOOK.BOOK_CODE 
WHERE INVENTORY.BRANCH_NUM = '3' OR INVENTORY.BRANCH_NUM != '3';

SELECT DISTINCT BOOK_CODE FROM WROTE WHERE SEQUENCE = '2';
